---
title: "About Stat 850"
---


# Course Description

Introductions to statistical computing packages and document preparation software. Topics include: graphical techniques, data management, Monte Carlo simulation, dynamic document preparation, presentation software.

# Course Goals
1. Learn how to use R and/or Python for data analysis, data processing, and data visualization.
2. Become familiar with the process, techniques, and goals of exploratory data analysis.
3. Create, assess, and debug code effectively.
    i. Use online resources to find software to perform a task, comparing approaches taken by competing programs.
    ii. Read error messages, find related problems in online forums, and isolate the conditions necessary to generate the error.
    iii. Generate minimum working examples or reproducible examples of errors in order to ask for help effectively.
4. Communicate statistical results using reproducible, dynamic tools. Understand the importance of reproducibility in scientific computation.

# Course Objectives
(what you should be able to do at the end of this course)

A.  Clean and format the data appropriately for the intended analysis or visualization method. (Goals: 1)

B.  Explore a data set using numerical and visual summaries, developing questions which can be answered using statistics. (Goals: 1, 2)

C.  Evaluate methods or software to assess relevance to a problem. Compare similar options to determine which are more appropriate for a given application (Goals: 1, 3)

D.  Test and debug software, using the following sequence: (Goals: 3, 4)
    1. Reproduce the error in a new environment,
    2. Create a minimal reproducible example,
    3. Research the error message and evaluate online resources for relevance,
    4. Ask for help, describing the error or problem appropriately.

E.  Document the data, methods, and results of an analysis using reproducible methods. (Goals: 1, 2, 4)


# Textbook

In keeping with the principles of this course, any course materials I develop will be made available on GitHub, in the (continuously evolving) [course textbook](https://srvanderplas.github.io/unl-stat850/). The book is laid out with the same structure as the course. In order to avoid duplicating content available elsewhere, where it is appropriate, I will link to relevant material available on other sites. This makes the course easier to maintain, but it also ensures you get the most relevant and up to date instructions.

In addition, you may find it useful to reference some of the following resources that I have consulted while assembling the textbook. Most are available online for free, though some require an institutional email address.

- [R for Data Science](https://r4ds.had.co.nz/)

- [Advanced R](http://adv-r.had.co.nz/)

- [Python for Everybody](https://www.py4e.com/html3/)

- [Python for Data Analysis](https://www.oreilly.com/library/view/python-for-data/9781449323592/) * 

- [Python Data Science Handbook](https://learning.oreilly.com/library/view/python-data-science/9781491912126/) *

\* Available online for free if you register with your UNL email address.
