---
title: "Simulation"
date: "2024-11-05"
categories: Slides
format: 
  revealjs:
    theme: default
---

## Homework & Project work

- due dates ... some are harder than others. 

I realize that RStudio was freezing up ... a lot. So this one is not as hard. 

Generally: you can (re-)submit assignments. If they are egregiously late, I will deduct a late penalty. 

Actually hard deadline: Monday after Thanksgiving, Dec 2 2024


---

## Remainder of the semester

- Only two more homework assignments!

Simulation & interactive graphics

- Project work!

https://posit.co/blog/closeread-prize-announcement/

---

## This week's big picture goal:

Bringing everything together - working on a project-like homework. 

---


## Today's Goals:

- In Canvas, follow the Github Classroom link to Homework 11

- Clone the repo for Homework 11 to your local machine

- Three deliverables in total: `pseudocode.qmd` (this week), `craps-code.qmd`, and `simulation.qmd`



----

## Resources

- [R cheat sheet](https://srvanderplas.github.io/stat-computing-r-python/files/Short-refcard.pdf)

- [python cheat sheet](https://srvanderplas.github.io/stat-computing-r-python/files/Python3_reference_cheat_sheet.pdf)





