---
title: "Backward Design Template"
format: pdf
---

# Stage 1: Desired Results

## Established Goals
<!-- The enduring understandings and learning goals of the lesson, unit, or course. -->

Create:

- research reports
- business reports
- executive summaries
- presentations

Use:

- dynamic documents
- reproducible code
- reference manager

Do:
- Counter misconceptions and errors in statistical reasoning
- Explain consequences of modeling for decision-making

## Transfer
<!-- Refers to how students will transfer the knowledge gained from the lesson, unit, or course and apply it outside of the context of the course. -->

Create reports and presentations describing statistical analyses (in course work, academia, industry, and public service).

## Meaning
### Understandings
<!-- Refers to the big ideas and specific understandings students will have when the complete the lesson, unit, or course. -->
Students will understand:

- reproducibility
- identification of the target audience
- communication strategies for different target audiences
- design strategies
- clear communication of statistical topics
- citations and referencing


### Essential Questions
<!-- Refers to the provocative questions that foster inquiry, understanding, and transfer of learning. These questions typically frame the lesson, unit, or course and are often revisited. If students attain the established goals, they should be able to answer the essential question(s). -->

- What common misconceptions do people have about statistical modeling and results?
- What common errors in understanding need to be addressed?
- How do visualizations contribute to the understanding of a model or result?
- What is the impact of the data collection, data cleaning and modeling decisions made during the course of a project on the interpretation of the results?

## Acquisition
### Knowledge
<!-- Refers to the key knowledge students will acquire from the lesson, unit, or course. -->

- Strategies for communicating statistical information clearly 
- Appropriate formatting and conventions for reporting and presenting statistical information
- Ethics of statistical communication
- 

### Skills
<!-- Refers to the key skills students will acquire from the lesson, unit, or course. -->

- Use of dynamic document software (LaTeX, pandoc, markdown, etc.) to integrate code, results, and written information
- Use of reference managers to support citations
- 

# Stage 2: Evidence and Assessment

## Evaluation Criteria
<!-- Refers to the various types of criteria that students will be evaluated on. -->
## Assessment Evidence

### Performance Tasks
<!-- Refers to the authentic performance task(s) that students will complete to demonstrate the desired understandings or demonstrate they have attained the goals. The performance task(s) are typically larger assessments that coalesce various concepts and understandings like large projects or papers. -->

### Other Evidence
<!-- Refers to other types of evidence that will show if students have demonstrated achievement of the desired results. This includes quizzes, tests, homework, etc. This is also a good point to consider incorporating self-assessments and student reflections. -->


# Stage 3: Learning Plan
<!-- This stage encompasses the individual learning activities and instructional strategies that will be employed. This includes lectures, discussions, problem-solving sessions, etc. -->