---
title: "Data Visualization"
date: 2023-10-13
---

Read: 

- [Chapter 3 of Data Feminism: On Rational, Scientific, Objective Viewpoints from Mythical, Imaginary, Impossible Standpoints](https://unl.alma.exlibrisgroup.com/leganto/public/01UON_LINC/citation/12340425610006387?auth=SAML)

Annotate with hypothes.is

Note: I assign chapters from Data Feminism because the authors made me think differently about data. I don't necessarily agree with everything they say, and I certainly don't expect you to agree with them either - I want you to stretch your brains and consider things from a different perspective. 

Content warning: This chapter contains an image of a largely unclothed body (PG or PG13 at most). 

Think about/comment on: 

- When do you think it is appropriate to create graphics which inspire and elevate emotion in viewers? When is this not appropriate?

- When you see a chart, do you think of it as a rhetorical tool or an objective display? What factors contribute to viewing the chart as one or the other?

- What ways do you think are effective for showing uncertainty in data? Have you seen any effective ways of visualizing uncertainty or missing data which are not mentioned in this chapter?
